// Autogenerated file for Kivy C configuration
#define __PY3 0
#define __USE_RPI 0
#define __USE_OPENGL_ES2 1
#define __USE_OPENGL_DEBUG 0
#define __USE_GLEW 0
#define __USE_SDL 0
#define __USE_SDL2 0
#define __USE_IOS 0
#define __USE_MESAGL 0
#define __USE_X11 0
#define __USE_GSTREAMER 0
#define __USE_AVFOUNDATION 0
